modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-only"
showAsResourcePack=false

[[mods]]
modId="justmissingblocks"
version="${version}"
displayName="Just Missing Blocks"
description='''
Adds missing wall, stairs, and slab variants for vanilla building blocks.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/JustMissingBlocks"

[[mixins]]
config="justmissingblocks.mixins.json"

[[dependencies.justmissingblocks]]
modId="neoforge"
type="required"
versionRange="[21.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.justmissingblocks]]
modId="minecraft"
type="required"
versionRange="[1.21.3]"
ordering="NONE"
side="BOTH"
